#!/usr/bin/env ts-node
/**
 * generate-flows.ts
 * Reads the expo-router app/ directory structure and generates skeleton
 * Maestro YAML flow files for each discoverable route.
 *
 * Usage:
 *   npx ts-node scripts/generate-flows.ts --app-dir app/ --output-dir tests/e2e/
 *   npx ts-node scripts/generate-flows.ts --app-dir app/ --output-dir tests/e2e/ --dry-run
 *   npx ts-node scripts/generate-flows.ts --app-dir app/ --app-id com.myapp.dev
 *
 * Replaces: screen-crawler.py
 */

import * as fs from 'fs';
import * as path from 'path';

// ─── Config ────────────────────────────────────────────────────────────────

const args = process.argv.slice(2);
function getArg(flag: string, fallback: string): string {
    const i = args.indexOf(flag);
    return i !== -1 ? args[i + 1] : fallback;
}

const APP_DIR = path.resolve(getArg('--app-dir', 'app'));
const OUTPUT_DIR = path.resolve(getArg('--output-dir', 'tests/e2e/generated'));
const APP_ID = getArg('--app-id', 'com.yourapp.dev');
const DRY_RUN = args.includes('--dry-run');

// ─── Helpers ───────────────────────────────────────────────────────────────

interface Route {
    /** Expo router file path relative to app/ */
    filePath: string;
    /** Derived route name (e.g. "profile-edit", "tab-home") */
    flowName: string;
    /** Screen testID prefix from convention */
    screenPrefix: string;
    /** Whether this is a tab screen */
    isTab: boolean;
}

const TESTID_MAP: Record<string, string> = {
    'index': 'home',
    'chats': 'chats',
    'earnings': 'earnings',
    'schedule': 'schedule',
    'me': 'me',
    '[id]': 'profile',
    'edit': 'profile-edit',
    'public': 'profile-public',
    'account-settings': 'account',
    'security-privacy': 'security',
    'help-support': 'help',
    'payout-preferences': 'payout',
    'payout-confirm': 'payout-confirm',
    'payout-success': 'payout-success',
    'verify': 'verify',
    'verify-status': 'verify-status',
    'verify-success': 'verify-success',
    'upload-id': 'upload-id',
    'face-scan': 'face-scan',
    'active': 'session',
    'rate': 'rate',
    'sos': 'sos',
    'add': 'contacts-add',
    'trusted': 'contacts-trusted',
    'booking-success': 'booking-success',
    'no-results': 'no-results',
};

function walkAppDir(dir: string, base: string = ''): Route[] {
    const routes: Route[] = [];
    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);
        const relPath = path.join(base, entry.name);

        if (entry.isDirectory()) {
            // Skip special dirs
            if (entry.name.startsWith('_') || entry.name === 'node_modules') continue;
            routes.push(...walkAppDir(fullPath, relPath));
        } else if (entry.name.endsWith('.tsx') && !entry.name.startsWith('_')) {
            const baseName = entry.name.replace('.tsx', '');
            const screenPrefix = TESTID_MAP[baseName] || baseName.replace(/[^a-z0-9]/g, '-');
            const isTab = relPath.includes('(tabs)');
            const flowName = isTab
                ? `tab-${screenPrefix}`
                : relPath.replace(/[\\/]/g, '-').replace(/\.tsx$/, '').replace(/[()]/g, '');

            routes.push({
                filePath: relPath,
                flowName: flowName.replace(/--+/g, '-').replace(/^-|-$/g, ''),
                screenPrefix,
                isTab,
            });
        }
    }
    return routes;
}

function generateYaml(route: Route): string {
    const safeFlow = route.flowName;
    const prefix = route.screenPrefix;

    return `appId: ${APP_ID}
---
# Auto-generated skeleton for: ${route.filePath}
# Screen prefix: ${prefix}
# Generated by generate-flows.ts — customize before running
# tags: [generated]

- launchApp
- waitForAnimationToEnd

# TODO: Add navigation commands to reach this screen
# Example if reachable from a tab:
# - tapOn:
#     id: "${prefix}-tab"

# Assert the screen loaded
- assertNotVisible: "Error"
- assertNotVisible: "undefined is not an object"
- assertNotVisible: "null is not an object"
- takeScreenshot: "${safeFlow}-loaded"

# TODO: Add element-specific assertions using testIDs
# Example:
# - assertVisible:
#     id: "${prefix}.main-content"
# - tapOn:
#     id: "${prefix}.primary-btn"
#     retryTapIfNoChange: 2
# - takeScreenshot: "${safeFlow}-after-action"

# Return to previous screen
- pressBack
- waitForAnimationToEnd
- assertNotVisible: "Error"
`;
}

// ─── Main ──────────────────────────────────────────────────────────────────

if (!fs.existsSync(APP_DIR)) {
    console.error(`❌ App directory not found: ${APP_DIR}`);
    process.exit(1);
}

const routes = walkAppDir(APP_DIR);
console.log(`📱 Found ${routes.length} screens in ${APP_DIR}\n`);

if (!DRY_RUN && !fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

let generated = 0;
let skipped = 0;

for (const route of routes) {
    const outputFile = path.join(OUTPUT_DIR, `${route.flowName}.yaml`);
    const yaml = generateYaml(route);

    if (DRY_RUN) {
        console.log(`[dry-run] Would generate: ${outputFile}`);
        console.log(yaml);
        console.log('---');
    } else {
        if (fs.existsSync(outputFile)) {
            console.log(`⏭  Skipping (exists): ${outputFile}`);
            skipped++;
        } else {
            fs.writeFileSync(outputFile, yaml, 'utf-8');
            console.log(`✅ Generated: ${outputFile}`);
            generated++;
        }
    }
}

if (!DRY_RUN) {
    console.log(`\n🎉 Done. Generated: ${generated}, Skipped: ${skipped}`);
    console.log(`📂 Output directory: ${OUTPUT_DIR}`);
    console.log(`\nNext steps:`);
    console.log(`  1. Review generated flows and add navigation commands`);
    console.log(`  2. Add testID-based assertions using references/testid-convention.md`);
    console.log(`  3. Run: maestro test ${OUTPUT_DIR}/`);
}
